### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by jjacobelli**
Add aarch64 support

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjacobelli** [comment]
@conda-forge-admin, please rerender

**Comment by jjacobelli** [comment]
@jakirkham @pitrou do you have some time to review this?

**Comment by jakirkham** [comment]
Thanks Jordan! 😄

Typically how we handle this is we add a package to the arch migration. Please see PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1566 ), which adds `pickle5`. Once merged this feedstock will get an autogenerated PR by the bot adding the additional architectures

Are there any other packages we should be adding to that list? 🙂

**Comment by jjacobelli** [comment]
> 
> 
> Thanks Jordan! 😄
> 
> Typically how we handle this is we add a package to the arch migration. Please see PR ( [conda-forge/conda-forge-pinning-feedstock#1566](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1566) ), which adds `pickle5`. Once merged this feedstock will get an autogenerated PR by the bot adding the additional architectures
> 
> Are there any other packages we should be adding to that list? 🙂

Oh ok, I will open the others PRs we need on this repo then 😄

**Comment by jakirkham** [comment]
Thanks Jordan! 😄 Feel free to cc me on those 🙂

**Comment by jakirkham** [comment]
The bot submitted PR ( https://github.com/conda-forge/pickle5-feedstock/pull/21 )

**Pull request closed without merging**
